services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: fl-tfvars-form-image
    container_name: fl-tfvars-form
    ports:
      - "8086:80"
    environment:
      - SECRET  # Will be passed at runtime
    networks:
      - fl-tfvars-network

  fl-ps-azure-func:
    build:
      context: ./azure-function
      dockerfile: Dockerfile
    image: fl-ps-azure-func-image
    container_name: fl-ps-azure-func
    environment:
      - AzureWebJobsScriptRoot=/home/site/wwwroot
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
      - SECRET          # Will be passed at runtime
      - GITHUB_URL      # Will be passed at runtime
      - GITHUB_TOKEN    # Will be passed at runtime
    networks:
      - fl-tfvars-network

networks:
  fl-tfvars-network:
    driver: bridge